#!/usr/bin/env python3
"""Generate C++ lookup tables for Corrode DSP engine.

Generates:
- MIDI note to frequency table (128 entries)
- tanh approximation accuracy report

Usage:
    python generate_tables.py
"""

import numpy as np


def generate_pitch_table():
    """Generate MIDI note to frequency lookup table."""
    print("// Auto-generated by tools/generate_tables.py")
    print("// MIDI note to frequency (Hz), A4 = 440 Hz")
    print(f"constexpr float kPitchTable[128] = {{")

    for i in range(128):
        freq = 440.0 * (2.0 ** ((i - 69) / 12.0))
        note_names = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
        name = f"{note_names[i % 12]}{i // 12 - 1}"
        end = "," if i < 127 else ""
        print(f"    {freq:12.6f}f{end}  // {i:3d}: {name}")

    print("};")


def verify_tanh_approx():
    """Verify accuracy of Padé tanh approximation."""
    x = np.linspace(-4, 4, 10000)
    exact = np.tanh(x)
    approx = x * (27 + x**2) / (27 + 9 * x**2)
    approx = np.clip(approx, -1, 1)

    error = np.abs(exact - approx)
    print(f"\ntanh approximation accuracy (|x| <= 4):")
    print(f"  Max absolute error: {np.max(error):.6f}")
    print(f"  Mean absolute error: {np.mean(error):.6f}")
    print(f"  Max error at x = {x[np.argmax(error)]:.3f}")

    # In the useful range |x| <= 3 (where we clamp)
    mask = np.abs(x) <= 3
    print(f"\ntanh approximation accuracy (|x| <= 3):")
    print(f"  Max absolute error: {np.max(error[mask]):.6f}")
    print(f"  Mean absolute error: {np.mean(error[mask]):.6f}")


if __name__ == "__main__":
    generate_pitch_table()
    verify_tanh_approx()
